version: '2'
services:
  jekyll:
      image: jekyll/jekyll:latest
      command: /bin/sh -c 'bundle install && jekyll build && jekyll serve --watch --incremental'
      environment:
        TZ: Europe/Warsaw
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll